version: '3.7'

services:
  bbrs:
    container_name: 'bbrs'
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env.docker
    volumes:
      - ./:/app
    restart: always
    ports:
      - "8000:8000"
#    networks:
#      - bb-network
#
#networks:
#  bb-network:
#    external:
#      name: bb-network
